GET http://localhost:3000/users

###

GET http://localhost:3000/users/5d1b39473f25393dec2c9f46


###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "sascha1"
}

###

DELETE http://localhost:3000/users/5d1b39473f25393dec2c9f46

###

PATCH http://localhost:3000/users/5d1b3deffa49401954be0541
Content-Type: application/json

{
    "name": "Sascha New"
}

###

POST http://localhost:3000/todos
Content-Type: application/json

{
    "todos": [{"user": "sascha", "title": "Learn Node", "category": "learn", "status": false, "text": "A test."},
    {"user": "sascha", "title": "Learn MongoDB", "category": "learn", "status": true, "text": "More tests."}]
}