GET https://apirestnodeexpressmongo.herokuapp.com/users

###

GET https://apirestnodeexpressmongo.herokuapp.com/users/5d1b47ec54388631f055b063


###

POST https://apirestnodeexpressmongo.herokuapp.com/users
Content-Type: application/json

{
    "name": "jeff"
}

###

DELETE https://apirestnodeexpressmongo.herokuapp.com/users/5d1b47ec54388631f055b063

###

PATCH https://apirestnodeexpressmongo.herokuapp.com/users/5d1b47ec54388631f055b063
Content-Type: application/json

{
    "name": "Sascha New"
}

### 
GET https://apirestnodeexpressmongo.herokuapp.com/todos

###

GET https://apirestnodeexpressmongo.herokuapp.com/todos/5d1b537ab8e64c1904472c1c


###

POST https://apirestnodeexpressmongo.herokuapp.com/todos
Content-Type: application/json

{
    "user": "sascha12",
    "text": "Learn ggg",
    "status": false
}

###

DELETE https://apirestnodeexpressmongo.herokuapp.com/todos/5d1b537ab8e64c1904472c1c

###

PATCH https://apirestnodeexpressmongo.herokuapp.com/todos/5d1b539ab8e64c1904472c1d
Content-Type: application/json

{
    "user": "sascha67"
}

###

GET https://apirestnodeexpressmongo.herokuapp.com/users
